name: Build

on:
  push:
    branches:
      - dev-build-linux-amd64
  pull_request:
    branches:
      - dev-build-linux-amd64
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRAALVM_VERSION: 22.3.0

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew clean
        ./gradlew build

    - name: Verify the tar command
      run: |
          tar --version
    - name: Build Native Image
      run: |
        ./gradlew nativeImage

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: native-image-ubuntu-amd64
        path: build/libs/
